<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function findAllOrderedByProduct()
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.product', 'ASC')

        ;
        $query = $qb->getQuery();

        return $query->execute();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function findOneById($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.id = :id')
            ->setParameter('id', $id)

        ;
        $query = $qb->getQuery();

        return $query->execute();
    }


    /**
     * @param $status
     * @return mixed
     */
    public function findByStatus($status)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.statusOrder = :statusOrder')
            ->setParameter('statusOrder', $status)

        ;
        $query = $qb->getQuery();

        return $query->execute();
    }

    /**
     * @return mixed
     */
    public function findAll()
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'DESC')

        ;
        $query = $qb->getQuery();

        return $query->execute();
    }
}
