Veta\HomeworkBundle\Entity\Brand:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\BrandRepository
    table: brand
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        brandName:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: brand_name
        discription:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
