Veta\HomeworkBundle\Entity\Category:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: category_name
        status:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
