Veta\HomeworkBundle\Entity\Feedback:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\FeedbackRepository
    table: feedback
    indexes:
        product_id:
            columns:
                - product_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        dateCreate:
            type: datetime
            nullable: false
            column: date_create
    manyToOne:
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
