Veta\HomeworkBundle\Entity\Orders:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\OrdersRepository
    table: orders
    indexes:
        status_order_id:
            columns:
                - status_order_id
        product_id:
            columns:
                - product_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreate:
            type: datetime
            nullable: false
            column: date_create
        comments:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        statusOrder:
            targetEntity: StatusOrder
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_order_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
