Veta\HomeworkBundle\Entity\Product:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\ProductRepository
    table: product
    indexes:
        category_id:
            columns:
                - category_id
        brand_id:
            columns:
                - brand_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productName:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: product_name
        discription:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        price:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        brand:
            targetEntity: Brand
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                brand_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
