Veta\HomeworkBundle\Entity\StatusOrder:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\StatusOrderRepository
    table: status_order
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        statusName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: status_name
    lifecycleCallbacks: {  }
