Veta\HomeworkBundle\Entity\Users:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\UsersRepository
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        pass:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        firstName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: last_name
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
